# Generated by Django 5.1.4 on 2024-12-13 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_category_is_active_category_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
