# Generated by Django 5.1.4 on 2024-12-12 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='user',
            new_name='user_id',
        ),
    ]
